export const NOTES_LIST_RESET = 'NOTES_LIST_RESET'

export const NOTES_LIST_PAGE_INCREASE = 'NOTES_LIST_PAGE_INCREASE'
export const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY'
export const SET_FILTER = 'SET_FILTER'

export const NOTES_GET_REQUEST = 'NOTES_GET_REQUEST'
export const NOTES_GET_SUCCESS = 'NOTES_GET_SUCCESS'
export const NOTES_GET_FAIL = 'NOTES_GET_FAIL'

export const NOTE_CREATE_REQUEST = 'NOTE_CREATE_REQUEST'
export const NOTE_CREATE_SUCCESS = 'NOTE_CREATE_SUCCESS'
export const NOTE_CREATE_FAIL = 'NOTE_CREATE_FAIL'

export const NOTE_UPDATE_REQUEST = 'NOTE_UPDATE_REQUEST'
export const NOTE_UPDATE_SUCCESS = 'NOTE_UPDATE_SUCCESS'
export const NOTE_UPDATE_FAIL = 'NOTE_UPDATE_FAIL'

export const NOTE_DELETE_REQUEST = 'NOTE_DELETE_REQUEST'
export const NOTE_DELETE_SUCCESS = 'NOTE_DELETE_SUCCESS'
export const NOTE_DELETE_FAIL = 'NOTE_DELETE_FAIL'

export const UPDATED_NOTE_SET = 'UPDATED_NOTE_SET'
export const UPDATED_NOTE_RESET = 'UPDATED_NOTE_RESET'