export const TAGS_GET_REQUEST = 'TAGS_GET_REQUEST'
export const TAGS_GET_SUCCESS = 'TAGS_GET_SUCCESS'
export const TAGS_GET_FAIL = 'TAGS_GET_FAIL'

export const TAG_CREATE_REQUEST = 'TAG_CREATE_REQUEST'
export const TAG_CREATE_SUCCESS = 'TAG_CREATE_SUCCESS'
export const TAG_CREATE_FAIL = 'TAG_CREATE_FAIL'

export const TAG_UPDATE_REQUEST = 'TAG_UPDATE_REQUEST'
export const TAG_UPDATE_SUCCESS = 'TAG_UPDATE_SUCCESS'
export const TAG_UPDATE_FAIL = 'TAG_UPDATE_FAIL'

export const TAG_DELETE_REQUEST = 'TAG_DELETE_REQUEST'
export const TAG_DELETE_SUCCESS = 'TAG_DELETE_SUCCESS'
export const TAG_DELETE_FAIL = 'TAG_DELETE_FAIL'