
export const notes = [
    {
        title: 'Alexandro Gonsales Injaritty',
        text: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Veritatis similique odio quo ut voluptas quod officia ipsa accusantium tempore enim.",
        color: '#fff',
        pinned: false,
        tags: ['buys', 'nina'],
    },
    {
        title: 'Rosamund',
        text: "Lorem ipsum Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione mollitia voluptatibus voluptas est reiciendis, accusantium libero necessitatibus cupiditate sint aspernatur.dolor sit  amet consectetur, adipisicing elit. Veritatis similique odio quo ut voluptas quod officia ipsa accusantium tempore enim.",
        color: '#fff',
        pinned: false,
        tags: ['buys', 'nina kraviz'],
    },
    {
        title: 'Shopping',
        text: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Veritatis similique odio quo ut voluptas quod officia ipsa accusantium tempore enim.",
        color: '#CAF7E3',
        pinned: false,
        tags: ['buys', 'nina kraviz'],
    },
    {
        title: 'Thuesday',
        text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione mollitia voluptatibus voluptas est reiciendis, accusantium libero necessitatibus cupiditate sint aspernatur.ritatis similique odio quo ut voluptas quod officia ipsa accusantium tempore enim.",
        color: '#fff',
        pinned: false,
        tags: ['buys', 'nina kraviz'],
    },
    {
        title: 'Captain daughter',
        text: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Veritatis similique odio quo ut voluptas quod officia ipsa accusantium tempore enim.Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione mollitia voluptatibus voluptas est reiciendis, accusantium libero necessitatibus cupiditate sint aspernatur.Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione mollitia voluptatibus voluptas est reiciendis, accusantium libero necessitatibus cupiditate sint aspernatur.",
        color: '#fff',
        pinned: false,
        tags: ['buys', 'nina kraviz'],
    },
    {
        title: 'React',
        text: "Lorem ipsum dolor sit amet t voluptas quod officia ipsa accusantium tempore enim.",
        color: '#b3d9ff',
        pinned: false,
        tags: ['buys', 'nina kraviz'],
    },
    {
        title: 'training plan',
        text: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Veritatis similique odio quo ut voluptas quod officia ipsa accusantium tempore enim.",
        color: 'rgb(255,180,180)',
        pinned: false,
        tags: ['buys', 'nina kraviz'],
    },
    {
        title: 'Alexandro Gonsales Injaritty',
        text: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Veritatis similique odio quo ut voluptas quod officia ipsa accusantium tempore enim.",
        color: '#fff',
        pinned: false,
        tags: ['buys'],
    },
    {
        title: 'Rosamund',
        text: "Lorem ipsum Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione mollitia voluptatibus voluptas est reiciendis, accusantium libero necessitatibus cupiditate sint aspernatur.dolor sit  amet consectetur, adipisicing elit. Veritatis similique odio quo ut voluptas quod officia ipsa accusantium tempore enim.",
        color: '',
        pinned: false,
        tags: ['buys', 'nina kraviz'],
    },
]